server:
  port: 0

spring:
  application:
    name: main-service

stats:
  server:
    url: http://stats-server

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/main
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: none

  jackson:
    serialization:
      write-dates-as-timestamps: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/

logging:
  level:
    org.zalando.logbook: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.springframework.transaction.interceptor: TRACE
    org.springframework.jdbc.datasource.init: DEBUG