CREATE TABLE IF NOT EXISTS participation_requests (
                                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                                                      requester_id BIGINT NOT NULL,
                                                      event_id BIGINT NOT NULL,
                                                      status VARCHAR NOT NULL,
                                                      created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);