server:
  port: 8080

management:
  endpoint:
    gateway:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    gateway:
      routes:
        - id: stat-server
          uri: lb://stats-server
          predicates:
            - Path=/hit/**,/stats/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**, /users/*/events/*/requests/**

        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/**