server:
  port: 9090

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/stats
    username: postgres
    password: postgres

  sql:
    init:
      mode: always

logging.level:
  ru.practicum: INFO
  org.springframework.jdbc.datasource.init: DEBUG